"use client";
import { useEffect, useState } from "react";
import AuthNav from "@/components/AuthNav";
import { copilotTypes, type CopilotType } from "@/lib/application-copilot";
const labels: Record<CopilotType, string> = { good_fit: "Good Fit", cover_letter: "Cover Letter", hr_message: "HR Message", cold_email: "Cold Email", follow_up: "Follow-up", interview_prep: "Interview Prep", highlight: "Highlight" };
export default function CopilotPage() {
  const [internshipId, setInternshipId] = useState<string | null>(null); const [type, setType] = useState<CopilotType>("good_fit"); const [content, setContent] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  useEffect(() => { setInternshipId(new URLSearchParams(window.location.search).get("internshipId")); }, []);
  async function generate() { if (!internshipId) { setError("Select a saved internship first."); return; } setLoading(true); setError(""); const response = await fetch("/api/copilot", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ internshipId, outputType: type }) }); const data = await response.json(); setLoading(false); if (!response.ok) { setError(data.error || "Unable to generate content."); return; } setContent(data.content); }
  return <main className="min-h-screen bg-slate-950 text-white"><nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><a href="/" className="text-xl font-bold">InternScout AI</a><AuthNav /></nav><section className="mx-auto max-w-4xl px-6 py-10"><h1 className="text-3xl font-bold">Application AI Copilot</h1><p className="mt-2 text-slate-400">Create internship-specific application content using your saved internship and latest resume.</p><div className="mt-6 flex flex-wrap gap-2">{copilotTypes.map((item) => <button key={item} type="button" onClick={() => { setType(item); setContent(""); }} className={`rounded-lg border px-3 py-2 text-sm ${type === item ? "border-blue-400 bg-blue-400/20 text-blue-200" : "border-slate-700 text-slate-300"}`}>{labels[item]}</button>)}</div><button type="button" onClick={() => void generate()} disabled={loading || !internshipId} className="mt-6 rounded-lg bg-blue-500 px-5 py-3 font-semibold disabled:opacity-60">{loading ? "Generating..." : "Generate"}</button>{error && <p className="mt-4 text-red-400">{error}</p>}{content && <div className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-6"><div className="flex justify-end"><button type="button" onClick={() => void navigator.clipboard.writeText(content)} className="text-sm text-blue-300">Copy</button></div><pre className="mt-3 whitespace-pre-wrap font-sans text-slate-200">{content}</pre></div>}</section></main>;
}
