"use client";

import Link from "next/link";
import AuthNav from "@/components/AuthNav";
import { useNotifications } from "@/components/NotificationBell";
import { useState } from "react";

export default function NotificationsPage() {
  const { notifications, authenticated, loading, error, markRead, markAllRead } = useNotifications();
  const [filter, setFilter] = useState<"all" | "unread" | "read">("all");
  const visible = notifications.filter((notification) => filter === "all" || (filter === "unread" ? !notification.is_read : notification.is_read));
  if (loading) return <main className="min-h-screen bg-slate-950 px-6 py-10 text-slate-300">Loading notifications...</main>;
  if (!authenticated) return <main className="min-h-screen bg-slate-950 px-6 py-10 text-white"><div className="mx-auto max-w-3xl"><p className="mb-4 text-red-400">Please sign in to view your notifications.</p><Link href="/login" className="rounded-lg bg-blue-500 px-4 py-2 text-sm font-semibold">Sign In</Link></div></main>;
  return <main className="min-h-screen bg-slate-950 px-6 py-10 text-white"><div className="mx-auto max-w-3xl"><header className="mb-8 flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-medium text-blue-400">InternScout AI</p><h1 className="mt-1 text-3xl font-bold">Notifications</h1></div><div className="flex items-center gap-4"><nav className="flex flex-wrap gap-4 text-sm text-slate-300"><Link href="/" className="hover:text-white">Search</Link><Link href="/dashboard" className="hover:text-white">Dashboard</Link><Link href="/recommendations" className="hover:text-white">Recommendations</Link><Link href="/tracker" className="hover:text-white">Tracker</Link><Link href="/alerts" className="hover:text-white">Alerts</Link></nav><AuthNav /></div></header>{error && <p className="mb-4 text-sm text-amber-300">{error}</p>}<div className="mb-5 flex flex-wrap items-center gap-2"><button type="button" onClick={() => setFilter("all")} className={`rounded-lg px-3 py-2 text-sm ${filter === "all" ? "bg-blue-500" : "bg-slate-800"}`}>All</button><button type="button" onClick={() => setFilter("unread")} className={`rounded-lg px-3 py-2 text-sm ${filter === "unread" ? "bg-blue-500" : "bg-slate-800"}`}>Unread</button><button type="button" onClick={() => setFilter("read")} className={`rounded-lg px-3 py-2 text-sm ${filter === "read" ? "bg-blue-500" : "bg-slate-800"}`}>Read</button>{notifications.some((notification) => !notification.is_read) && <button type="button" onClick={() => void markAllRead()} className="ml-auto text-sm text-blue-300 hover:text-blue-200">Mark all as read</button>}</div>{visible.length === 0 ? <div className="rounded-2xl border border-slate-800 bg-slate-900 p-6 text-slate-300">{filter === "unread" ? "You have no unread notifications." : "No notifications yet."}</div> : <div className="space-y-3">{visible.map((notification) => <article key={notification.id} className={`rounded-2xl border border-slate-800 bg-slate-900 p-5 ${!notification.is_read ? "border-blue-400/40" : ""}`}><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold">{notification.title}</h2><p className="mt-1 text-sm text-slate-300">{notification.message}</p><p className="mt-2 text-xs text-slate-500">{new Date(notification.created_at).toLocaleString()}</p></div>{!notification.is_read && <span className="rounded-full bg-blue-400/20 px-2 py-1 text-xs text-blue-200">Unread</span>}</div><div className="mt-3 flex gap-4 text-sm">{notification.link && <Link href={notification.link} onClick={() => void markRead(notification.id)} className="text-blue-300 hover:text-blue-200">View details</Link>}{!notification.is_read && <button type="button" onClick={() => void markRead(notification.id)} className="text-slate-400 hover:text-white">Mark as read</button>}</div></article>)}</div>}</div></main>;
}
