"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

const features = [["Smart Internship Discovery", "Discover internships from multiple sources."], ["Resume Match", "Compare your resume against internship requirements."], ["AI Application Copilot", "Get personalized application assistance."], ["Personalized Dashboard", "Track saved opportunities and application progress."], ["Smart Filtering", "Search by role, location, skills, and preferences."]] as const;

export default function HomePage() {
  const [authenticated, setAuthenticated] = useState(false);
  useEffect(() => { void createClient().auth.getUser().then(({ data }) => setAuthenticated(Boolean(data.user))); }, []);
  const destination = authenticated ? "/dashboard" : "/login";
  return <main className="min-h-screen bg-slate-950 text-white">
    <nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><Link href="/" className="text-xl font-bold">InternScout AI</Link><div className="flex items-center gap-5 text-sm text-slate-300"><a href="#features" className="hidden hover:text-white sm:inline">Features</a><a href="#how-it-works" className="hidden hover:text-white sm:inline">How It Works</a>{authenticated ? <Link href="/dashboard" className="rounded-lg bg-blue-500 px-4 py-2 font-semibold text-white">Dashboard</Link> : <><Link href="/login" className="hover:text-white">Sign In</Link><Link href="/login?mode=signup" className="rounded-lg bg-blue-500 px-4 py-2 font-semibold text-white">Get Started</Link></>}</div></nav>
    <section className="mx-auto max-w-6xl px-6 pb-20 pt-20 text-center sm:pt-28"><p className="text-sm font-semibold uppercase tracking-widest text-blue-400">Internship discovery, made personal</p><h1 className="mx-auto mt-5 max-w-4xl text-4xl font-bold tracking-tight sm:text-6xl">Find internships. Match your resume. Apply smarter.</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-400">InternScout AI discovers relevant internships, analyzes how well your resume matches, and helps you prepare stronger applications.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><Link href={destination} className="rounded-lg bg-blue-500 px-6 py-3 font-semibold hover:bg-blue-600">Get Started</Link><Link href={destination} className="rounded-lg border border-slate-700 px-6 py-3 font-semibold text-slate-200 hover:bg-slate-900">Explore Opportunities</Link></div></section>
    <section id="features" className="mx-auto grid max-w-6xl gap-4 px-6 pb-20 sm:grid-cols-2 lg:grid-cols-5">{features.map(([title, text]) => <article key={title} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></article>)}</section>
    <section id="how-it-works" className="border-y border-slate-800 bg-slate-900/50 px-6 py-16"><div className="mx-auto max-w-4xl"><h2 className="text-center text-3xl font-bold">How it works</h2><div className="mt-10 grid gap-6 sm:grid-cols-3">{[["01", "Create your account"], ["02", "Discover internships that match your interests"], ["03", "Analyze your resume and prepare your application"]].map(([number, text]) => <div key={number}><p className="text-sm font-bold text-blue-400">{number}</p><p className="mt-2 font-semibold">{text}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-4xl px-6 py-20 text-center"><h2 className="text-3xl font-bold">Your next internship could be one search away.</h2><Link href={destination} className="mt-7 inline-block rounded-lg bg-blue-500 px-6 py-3 font-semibold hover:bg-blue-600">Start Finding Internships</Link></section>
    <footer className="border-t border-slate-800 px-6 py-8 text-center text-sm text-slate-500"><p className="font-semibold text-slate-300">InternScout AI</p><p className="mt-2">Discover better opportunities and apply with confidence.</p><p className="mt-4">© 2026 InternScout AI</p></footer>
  </main>;
}
