export type SuggestionType = "roles" | "skills" | "locations";

export const fallbackSuggestions: Record<SuggestionType, string[]> = {
  roles: [
    "Software Engineer Intern",
    "Software Developer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Data Analyst",
    "Data Scientist",
    "Machine Learning Engineer",
    "AI Engineer",
    "DevOps Engineer",
    "Cybersecurity Intern",
    "Research Intern",
  ],
  skills: [
    "Python",
    "Java",
    "C++",
    "JavaScript",
    "TypeScript",
    "React",
    "Next.js",
    "Node.js",
    "HTML",
    "CSS",
    "Tailwind CSS",
    "SQL",
    "PostgreSQL",
    "MongoDB",
    "Git",
    "Docker",
    "AWS",
    "REST APIs",
    "Data Structures",
    "Algorithms",
    "Machine Learning",
    "Generative AI",
    "LLM",
    "TensorFlow",
    "PyTorch",
    "Pandas",
    "NumPy",
  ],
  locations: [
    "Remote",
    "Bengaluru",
    "Hyderabad",
    "Pune",
    "Mumbai",
    "Delhi",
    "Noida",
    "Gurgaon",
    "Chennai",
    "Kolkata",
    "Ahmedabad",
    "Kochi",
    "Jaipur",
    "India",
  ],
};
